# Generated by Django 2.0.3 on 2018-03-07 12:44

import datetime
from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alamenuud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sundmus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimetus', models.CharField(max_length=200)),
                ('sisu', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Sündmused',
            },
        ),
        migrations.AlterModelOptions(
            name='alamenuu',
            options={'verbose_name_plural': 'Alamenüüd'},
        ),
        migrations.RemoveField(
            model_name='alamenuu',
            name='tiitel',
        ),
        migrations.AlterField(
            model_name='alamenuu',
            name='sisu',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
