# Generated by Django 2.0.3 on 2018-03-07 13:20

import datetime
from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alamenuud', '0002_auto_20180307_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uudis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimetus', models.CharField(max_length=200)),
                ('sisu', froala_editor.fields.FroalaField()),
                ('kuupaev', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Uudised',
            },
        ),
    ]
