# Generated by Django 2.0.3 on 2018-03-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alamenuud', '0003_uudis'),
    ]

    operations = [
        migrations.AddField(
            model_name='uudis',
            name='pilt',
            field=models.URLField(default='/static/alamenuud/logo.png'),
        ),
    ]
