# Generated by Django 2.0.3 on 2018-03-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alamenuud', '0004_uudis_pilt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uudis',
            name='pilt',
        ),
        migrations.AddField(
            model_name='uudis',
            name='tutvustus',
            field=models.TextField(default=''),
        ),
    ]
