# Generated by Django 2.0.3 on 2018-03-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alamenuud', '0005_auto_20180307_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uudis',
            name='kuupaev',
            field=models.DateTimeField(blank=True, default='2018-03-08'),
        ),
    ]
