# Generated by Django 2.0.3 on 2018-03-08 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alamenuud', '0006_auto_20180308_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uudis',
            name='kuupaev',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
